apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
  namespace: muchtodo
data:
  PORT: "8080"
  DB_NAME: "muchtodo"
  MONGO_URI: "mongodb://root:example@mongodb-service:27017/muchtodo?authSource=admin"
  JWT_EXPIRATION_HOURS: "72"
  ENABLE_CACHE: "false"
  LOG_LEVEL: "info"
  LOG_FORMAT: "json"
